#!/bin/bash
username=`head -n1 $1 | tail -1`   
password=`head -n2 $1 | tail -1`

HOST='209.159.147.190'
USER='routervp_routervp'
PASS='KuD%2fsq4I+l'
DB='routervp_routervp'


PRIVATE="username='$username' AND decrypted_password='$password' AND u_type='1' AND status='1'"

Query="SELECT username FROM vgax_users WHERE $PRIVATE"

auth_vpn=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`

if [ "$auth_vpn" == "$username" ]; then
	 echo "user : $username"
	 echo "authentication ok."
	exit 0
else
	echo "authentication failed."
	exit 1
fi
