#!/bin/bash
username=`head -n1 $1 | tail -1`   
password=`head -n2 $1 | tail -1`

### MySQL Remote Server side
DatabaseHost='209.159.147.190';
DatabaseName='routervp_routervp';
DatabaseUser='routervp_routervp';
DatabasePass='KuD%2fsq4I+l';
DatabasePort='3306';
#####################
#####################


PRIVATE="username='$username' AND decrypted_password='$password' AND u_type='1' AND status='1'"

Query="SELECT username FROM vgax_users WHERE $PRIVATE"

auth_vpn=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`

if [ "$auth_vpn" == "$username" ]; then
	 echo "user : $username"
	 echo "authentication ok."
	exit 0
else
	echo "authentication failed."
	exit 1
fi
